### ISSUE TITLE
x64 Version

### ISSUE THREAD

**Issue by mikechelsea** [james34602/UPX-Visual-Studio#1]
Hi , can you please release a setup for x64 build ?

**Comment by james34602** [comment]
Probably not, x64 build is not very useful.
I don't see any executable will exceed 1Gb.

**Comment by NeoTrix2000** [comment]
@james34602 it's useful dude , I'm interested in x64 build too , I tried to build it my own but I got stuck in libraries .
we'll be very grateful if you create a 64 build setup. cheer^^

**Comment by in7egral** [comment]
Added x64 support in #3

**Comment by UnlimitedChild** [comment]
23 Jan 2020 » UPX 3.96 released

**Comment by james34602** [comment]
@UnlimitedChild 
I need to take a look to the commit of official UPX

**Comment by UnlimitedChild** [comment]
> @UnlimitedChild
> I need to take a look to the commit of official UPX

Hi,

do you have any results?

Thanks!

**Comment by james34602** [comment]
I don't have much time on the project...

**Comment by james34602** [comment]
I finally merge it.
I don't have time and resource to test the compression integrity over different platform.
Let you guys do it!
