### ISSUE TITLE
how can i edit the UPX pe header in conf.h

### ISSUE THREAD

**Issue by timwhitez** [james34602/UPX-Visual-Studio#5]
i means which lines should i change

**Comment by james34602** [comment]
Sorry for inconvenience, back in the day update to 3.96, I forget to add back header shortcut, the conf.h have now been updated.

However, there is a "UPX0" can't really be modified simply by recalculate magic number from ASCII, post editing on compressed executable could be the way to achieve that.
(You don't really need a hex editor, Notepad++ will able to do the job on compressed .exe)
