### ISSUE TITLE
Cannot open include file: 'windows.h': No such file or directory

### ISSUE THREAD

**Issue by gebrochen** [james34602/UPX-Visual-Studio#6]
As the title suggests, attempting to open the main upx-3.94-WithDependancy.sln in visual studio produces the following error at compile time:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'windows.h': No such file or directory
```
![image](https://user-images.githubusercontent.com/75397480/102172328-6b633600-3e4d-11eb-8b36-78f4a01eb116.png)

Attempted to fix this by following -> https://stackoverflow.com/questions/12748896/cannot-open-windows-h-in-microsoft-visual-studio

however it continues to have this error.

Additional Info:
Using visual studio 2019

**Comment by james34602** [comment]
Just the Windows.h or plenty more standard library?

**Comment by gebrochen** [comment]
Just windows.h which is strange since I can compile any other project that requires the standard windows library.

**Comment by james34602** [comment]
Upgrade Visual studio project/solution to more recent SDK.

I think that's worth to try, I guess problem is somehow related to VC compiler or Windows SDK version.

**Comment by gebrochen** [comment]
This was after I upgraded the project to the most recent version. I'm not sure why but actually keeping it as the downgraded version seems to succeed when building. Thanks Microsoft 

Steps for fixing the issue listed above:
1. When opening visual studio solution don't hit upgrade and deselect everything.
